# .github/CD.yml for Bundl Android App
#
# Used by .github/workflows/build-and-release.yml
# Configuration for environment variable and file management
#

# List of environment variables this app needs from the envs repo's env_vars/ directory
# These will be read from envs repo and made available to the workflow
required_env_vars:
  - APK_MANAGER_SECRET_KEY
# Environment folder in the envs repo that contains files for this project
env_subpath: bundl_app  # Points to the bundl_app folder we just created

# This CD.yml is specifically for the Android app build process
# The bundl_app/copy.sh script will handle copying local.properties and other Android-specific files
